services:
  bash:
    image: learncli/bash
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  comp211:
    # From github.com:comp211/comp211-container
    image: learncli/comp211:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  comp530:
    # From github.com:comp211/comp211-container
    image: learncli/comp211:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  multiarch:
    # From github.com:comp211/don/multiarch
    image: learncli/multiarch:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  comp730:
    # From github.com:comp730-s23/comp730-container
    image: learncli/comp730:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
