services:
  comp211:
    # From github.com:comp211/comp211-container
    image: learncli/comp211:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-../}"
        target: /mnt/learncli
    command: /bin/sh -c "while sleep 1000; do :; done"
